Advanture/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/urls.py
from django.urls import path
from . import views
from django.urls import include

app_name = 'myapp1'
urlpatterns = [
    path('', views.login_request, name='login'),
    path('myapp/user-profile/', views.mainpg , name='user_profile'),
    path('myapp/client-profile/', views.clientprofilepg, name='client_profile'),
    path('myapp/homepage/', views.homepage, name='homepage'),
    path('myapp/signup', views.create_client, name='createClient'),
    path('myapp/fp', views.forgot_password, name='forgotpassword'),
    path('myapp/createevent', views.create_event, name='createevent'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('myapp/advanture/<int:type_id>/', views.adventures_by_type, name='adventuresdetail'),
    path('myapp/bookingevent/<int:event_id>/', views.bookevent, name='bookevent'),
    path('myapp/generatepdf/<int:event_id>', views.generatepdf, name='generatepdf'),
    path('myapp/search', views.search, name="search"),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings


class Client(User):
    IsAdmin = models.BooleanField(null=False)

    # PhoneNumber = models.PositiveIntegerField(null=False)
    class Meta:
        verbose_name = "Client"


class PasswordReset(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=64, unique=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.username} - {self.token}'

    def send_reset_email(self):
        subject = 'Reset your password'
        message = f'Click the following link to reset your password: http://127.0.0.1:8000/reset_password/{self.token}/'
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [self.user.email],
            fail_silently=False,
        )


class AdventureType(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Adventure(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    type = models.ForeignKey(AdventureType, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class CreateEvent(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    advanture = models.ForeignKey(Adventure, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/myapp/pics')
    location = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    event_date = models.DateTimeField()

    def __str__(self):
        return self.name


class EventBooking(models.Model):
    event = models.ForeignKey(CreateEvent, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booked_at = models.DateTimeField(auto_now_add=True)
    number_of_people = models.IntegerField(default=1)
    total_amount_paid = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return f'{self.user.username} booked {self.event.name}'

    def get_absolute_url(self):
        return reverse('event_booking_detail', args=[str(self.id)])

myapp/forms.py
from django import forms
from django.forms import HiddenInput
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe

from .models import Client, AdventureType, Adventure, CreateEvent, EventBooking


class ClientForm(forms.ModelForm):
    confirmpassword = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Client
        fields = ['username', 'email', 'password', 'confirmpassword', 'first_name', 'last_name', 'IsAdmin']
        widgets = {
            'password': forms.PasswordInput()
        }


class CreateEventForm(forms.ModelForm):
    class Meta:
        model = CreateEvent
        fields = ['name', 'description', 'advanture', 'location', 'price', 'event_date', 'img']
        widgets = {
            'event_date': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form__input'}),
            'img': forms.FileInput(attrs={'class': 'form__input'}),
            'name': forms.TextInput(attrs={'class': 'form__input'}),
            'location': forms.TextInput(attrs={'class': 'form__input'}),
            'description': forms.Textarea(attrs={'class': 'form__input', }),
            'advanture': forms.Select(attrs={'class': 'form__input', }),
            'price': forms.NumberInput(attrs={'class': 'form__input', })
            # 'price': forms.TextInput(attrs={'class': 'form__input'}),
        }

    def __init__(self, *args, **kwargs):
        super(CreateEventForm, self).__init__(*args, **kwargs)
        self.fields['advanture'].queryset = Adventure.objects.all()


class EventBookingForm(forms.ModelForm):
    class Meta:
        model = EventBooking
        fields = ['number_of_people']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['number_of_people'].widget.attrs.update({'class': 'form-control'})

myapp/views.py
import datetime
import uuid
import re
from io import BytesIO
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, FileResponse
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.utils import timezone
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from .forms import ClientForm, CreateEventForm
from django.contrib.auth import login, authenticate, logout  # add this
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm  # add this
from django.template import RequestContext
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from myapp.forms import ClientForm
from myapp.models import Client, PasswordReset, AdventureType, Adventure, CreateEvent


# Create your views here.


def login_request(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                messages.success(request, "You are now logged in :)")
                return redirect('myapp1:homepage')
            else:
                return HttpResponse('Your account is disabled.')
        else:
            messages.error(request, "Wrong Username OR Passwords ")
            return redirect('myapp1:login')
    else:
        form1 = authenticate()
        form2 = ClientForm()
        return render(request, 'myapp/login.html', {'form1': form1, 'form2': form2})



@login_required
def homepage(request):
    msg = "Welcome to Adventures"
    types = AdventureType.objects.all()
    events = CreateEvent.objects.all()
    return render(request=request, template_name="myapp/homepage.html", context={"msg": msg, 'types': types})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reversed(('login')))


def create_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        # if form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        confirmpassword = request.POST['confirmpassword']
        email = request.POST['email']
        if User.objects.filter(username=username).exists():
            form.add_error('username', 'Username already exists.')
            messages.error(request, "Username Not Available")
            return redirect('myapp1:login')

        elif password != confirmpassword:
            form.add_error('confirmpassword', 'Passwords do not match.')
            messages.error(request, "Passwords do not match")
            return redirect('myapp1:login')

        elif not re.match(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$', email):
            form.add_error('email', 'Invalid email address')
            messages.error(request, "Invalid email address")
            return redirect('myapp1:login')

        else:
            client = form.save(commit=False)
            client.set_password(password)
            client.save()
            messages.success(request, "Signup Successful!")
            return redirect('myapp1:login')
        # else:
        #     # Handle form validation errors
        #     messages.warning(request, "Form validation error")
        #     return render(request, 'myapp/login.html')

    else:
        form2 = ClientForm()
        return render(request, 'myapp/login.html', {'form2': form2})


def forgotpassword(request):
    return render(request, 'myapp/forgotpassword.html')


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        user = User.objects.filter(email=email).first()
        print(user)
        if user is not None:
            while True:
                token = uuid.uuid4().hex
                if not PasswordReset.objects.filter(token=token).exists():
                    break
            password_reset = PasswordReset.objects.create(user=user, token=token)
            print(password_reset)
            password_reset.send_reset_email()
            messages.success(request, 'An email has been sent with instructions to reset your password.')
            return redirect('myapp1:login')

        messages.error(request, 'There is no account with that email.')
    return render(request, 'myapp/forgotpassword.html')


def reset_password(request, token):
    reset_token = PasswordReset.objects.filter(token=token).first()

    if reset_token is None or reset_token.created_at < timezone.now() - timezone.timedelta(hours=1):
        messages.error(request, 'This link is no longer valid. Please try resetting your password again.')
        return redirect('myapp1:forgotpassword')

    if request.method == 'POST':
        password = request.POST['password']
        reset_token.user.set_password(password)
        reset_token.user.save()
        reset_token.delete()
        messages.success(request, 'Your password has been reset. Please log in with your new password.')
        return redirect('myapp1:login')

    return render(request, 'myapp/resetpassword.html')


@login_required
def create_event(request):
    if request.method == 'POST':
        form = CreateEventForm(request.POST)
        event_date_str = request.POST['event_date']
        event_date = datetime.datetime.strptime(event_date_str, '%Y-%m-%dT%H:%M')
        form.instance.client = request.user.client
        if event_date > datetime.datetime.now():
            if form.is_valid():
                event = form.save(commit=False)
                event.client = request.user.client
                event.save()
                messages.success(request, 'Event created successfully.')
                return redirect('myapp1:homepage')
        else:
            messages.error(request, '-----invalid EventDate-----')
            return redirect('myapp1:createevent')
    else:
        form = CreateEventForm()
    return render(request, 'myapp/createevent.html', {'form': form})


def adventures_by_type(request, type_id):
    type = get_object_or_404(AdventureType, pk=type_id)
    adventures = Adventure.objects.filter(type=type)
    events = {}
    print()
    for adventure in adventures:
        events[adventure.name] = CreateEvent.objects.filter(advanture=adventure)
        temp = CreateEvent.objects.filter(advanture=adventure)

        for ev in temp:
            # ev.img = request.build_absolute_uri(ev.img)
            ev.img = ' http://127.0.0.1:8000/' + str(ev.img)
            print(ev.img)
        events[adventure.name] = temp

        # events = CreateEvent.objects.filter(advanture__in=adventures)
    return render(request, 'myapp/advanturedetail.html', {'adventures': adventures, 'events': events})


#######################################################################################################################

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template.loader import get_template
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from decimal import Decimal
from .forms import EventBookingForm
from .models import CreateEvent, EventBooking


# def book_event(request, event_id):
#     event = CreateEvent.objects.get(id=event_id)
#     print(request.method)
#     if request.method == 'POST':
#         form = EventBookingForm(request.POST)
#         print(form.errors)
#         if form.is_valid():
#             booking = form.save(commit=False)
#             booking.event = event
#             booking.user = request.user
#             booking.total_amount_paid = Decimal(booking.number_of_people) * event.price
#             booking.save()
#             # return render(request, 'myapp/bookingconfirmation.html',{'event': event, 'booking': booking})
#             # Generate PDF file
#             return render(request, 'myapp/bookingconfirmation.html', {'event': event, 'booking': booking})
#             template = get_template('myapp/bookingconfirmation.html')
#             context = {'event': event, 'booking': booking}
#             html = template.render(context)
#             pdf_file = open(f'booking_confirmation_{booking.id}.pdf', 'wb')
#             pdf_file.write(html.encode('utf-16'))
#             pdf_file.close()
#             print(pdf_file)
#             # Save the PDF file to the storage
#             filename = default_storage.save(pdf_file.name, ContentFile(open(pdf_file.name, 'rb').read()))
#             print(filename)
#             # Download the PDF file
#             response = FileResponse(open(pdf_file.name, 'rb'), content_type='Downloads/pdf')
#             print(response)
#             response['Content-Disposition'] = f'attachment; filename="{pdf_file.name}"'
#             return response
#     else:
#         form = EventBookingForm()
#     return render(request, 'myapp/book_event.html', {'event': event, 'form': form})
#

def bookevent(request, event_id):
    event = CreateEvent.objects.get(id=event_id)
    print("Method: , ", request.method)
    if request.method == 'POST':
        form = EventBookingForm(request.POST)
        print(form.errors)
        booking_id = ''
        print(event)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.event = event
            booking.user = request.user
            booking.total_amount_paid = Decimal(booking.number_of_people) * event.price
            booking_id = booking.save()
            # booking_id = {booking.id}
            event_id = event.id
            name = event.name
            user = event.client.username
            ticket_size = int(request.POST['number_of_people'])

templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <script type="text/javascript" src="{% static "myapp/index.js" %}"></script>
    <title> Adventurous  - {% block title %} Welcome! {% endblock %}</title>
</head>
<body>
<div>
    {% include 'myapp/messages.html' %}
    {% block body_block %}*** {% endblock %}
    <ul>
        <li class="hbar1"><a href="{% url 'myapp1:homepage'%}"> Home </a></li><br>
        <li class="hbar1"></li></ul>
</div> <hr />
<div>
{#    <ul>#}
{#        <li class="hbar1"><a href="{% url 'myapp1:login'%}"> Home </a></li><br>#}
{#         <li class="hbar1"></li>#}
{#</ul>#}
    <button><a href="{% url 'myapp1:login'%}"> Logout </a></button>
</div>
    <script>
    setTimeout(function(){
        var msg = document.getElementById("msg");
        if (msg) {
            msg.parentNode.removeChild(msg);
        }
    }, 3000);
</script>
</body>
</html>

templates/myapp/book_event.html
{% block content %}
    <h2>Event:{{ event.name }}</h2>
    <p>Description:{{ event.description }}</p>
    <p>Price: ${{ event.price }}CAD/pr</p>
    <p>Organised By:{{ event.client.username }}</p>
    <p>Location:{{ event.location }}</p>
    <p>Event Date:{{ event.event_date }}</p>
    <hr>
    <h1 class="align-center">Book NOW !!</h1>
    <form method="POST" action="{% url 'myapp1:bookevent' event.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.number_of_people.id_for_label }}">book For {{ form.number_of_people }} people</label>

        </div>
        <br>
        <button type="submit" class="btn btn-primary">Book Now</button>
    </form>
{% endblock %}

templates/myapp/createevent.html
{% extends "myapp/new_base.html" %}
{% include 'myapp/messages.html' %}
{% block body_block %}
    <section class="section-book" id="create_event_form">
        <div class="row">
            <div class="book">
                <div class="book__form">
                    <form action="#" class="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h2 class="heading-secondary u-padding-bottom-medium">
                            Create Adventure
                        </h2>

                        <div class="form__group">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="form__group">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                        <div class="form__group">
                            {{ form.advanture.label_tag }}
                            {{ form.advanture }}
                        </div>
                        <div class="form__group">
                            {{ form.client.label_tag }}
                            {{ form.client }}
                        </div>
                        <div class="form__group">
                            {{ form.img.label_tag }}
                            {{ form.img }}
                        </div>
                        <div class="form__group">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="form__group">
                            {{ form.price.label_tag }}
                            {{ form.price }}
                        </div>
                        <div class="form__group">
                            {{ form.event_date.label_tag }}
                            {{ form.event_date }}
                        </div>
                        <div class="form__group">
                            <button style="margin-top: 3em" class="btn btn--greenfill" type="submit">Create &rarr;</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{#    <h1>Create Adventure</h1>#}
{#    <form method="post" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Create</button>#}
{#    </form>#}
{% endblock %}

templates/myapp/footer.html
{% load static%}
<style>
    .rowfoot{
        text-align: center;
        align-items: center;
    }
</style>
   <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <!-- <link rel="stylesheet" href="css/icon-font.css"> -->
        <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'myapp/img/favicon.png' %}">
<footer class="footer">
            <div class="footer__logo-box u-center-text">
                <img srcset="{% static 'myapp/img/logo-white.png' %} 1x, {% static 'myapp/img/logo-white.png' %} 2x" alt="Logo" class="footer__logo">
            </div>
            <div class="rowfoot">
                <div class="col-2-of-3">
                    <div class="footer__nav">
                        <ul>
                            <li class="footer__item"><a href="#" class="footer__link">Company</a></li>
                            <li class="footer__item"><a href="#" class="footer__link">Contact us</a></li>
                            <li class="footer__item"><a href="#" class="footer__link">Careers</a></li>
                            <li class="footer__item"><a href="#" class="footer__link">Privacy policy</a></li>
                            <li class="footer__item"><a href="#" class="footer__link">Terms</a></li>
                        </ul>
                    </div>
                </div>
{#                <div class="col-1-of-2">#}
{#                    <p class="footer__copyright">#}
{#                        Built by <a href="#" class="footer__link">JONAS SCHMEDTMANN</a> for his online course <a href="#" class="footer__link">ADVANCED CSS AND SASS</a>. Copyright © by Jonas Schmedtmann. You are 100% allowed to use this webpage for both personal and commercial use, but NOT to claim it as your own design. A credit to the original author, Jonas Schmedtmann, is of course highly appreciated!#}
{#                    </p>#}
{#                </div>#}
            </div>

        </footer>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="{% static 'myapp/index.js' %}"></script>

templates/myapp/header.html
{% load static %}
   <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

        <!-- <link rel="stylesheet" href="css/icon-font.css"> -->
        <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'myapp/img/favicon.png' %}">
<style>
    ul{
        list-style-type: none;
    }
</style>
 <div class="navigation">
            <input type="checkbox" class="navigation__checkbox" id="navi-toggle">
            <label for="navi-toggle" class="navigation__button">
                <span class="navigation__icon">&nbsp;</span>
            </label>

            <div class="navigation__background">&nbsp;</div>

            <nav class="navigation__nav">
                <ul class="navigation__list">
                    <label for="navi-toggle">
                        <li class="navigation__item"><label for="navi-toggle"><a href="{% url "myapp1:login" %}" class="navigation__link">Log-in</a></label></li>
                        <li class="navigation__item"><a href="{% url 'myapp1:homepage'%}" class="navigation__link">Adventures</a></li>
                        <li class="navigation__item"><a href="#stories" class="navigation__link">stories</a></li>
                        <li class="navigation__item"><a href="{% url 'myapp1:user_profile' %}" class="navigation__link">User Profile</a></li>
                        <li class="navigation__item"><a href="{% url 'myapp1:client_profile' %}" class="navigation__link">Event creator's Profile</a></li>
{#                        <li class="navigation__item"><a href="{% url 'myapp1:adventuresdetail' type_id %}" class="navigation__link">Book now</a></li>#}
                    </label>
                </ul>
            </nav>
        </div>


 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="{% static 'myapp/index.js' %}"></script>

templates/myapp/homepage.html
{% extends 'myapp/new_base.html' %}
{% load static %}
{% block body_block %}
    <title>HomePage</title>
    <header class="header">
        {#            <div class="header__logo--box">#}
        {#                <img src="{% static 'myapp/img/logo-white.png' %}" alt="logo">#}
        {#            </div>#}

        <div class="header__text--box">
            <h1 class="header__primary"></h1>
            <span class="header__primary--main"> The Trek-Tix</span>
            <span class="header__primary--sub">Embrace The Thrill!
                    </span>
            <form action="{% url "myapp1:search" %}" method="GET">

                <input type="text" id="search-button" name="query" value="{{ query }}"
                       placeholder="Explore Adventures..."
                       class="btn btn--animated search-btn-expanded">
                <input type="submit" style="visibility: hidden">
            </form>


        </div>
    </header>
    {% if events|length > 0 %}
        <div id="search_results" class="row" style="min-width: 95vw; padding-left: 5em">

            {% for event in events %}
                <div class="col-1-of-4" style="margin-bottom: 5em; ">
                    <div class="card">
                        <div class="card__side card__side--front">
                            <div class="card__picture card__picture-2">
                                &nbsp;
                            </div>
                            <div class="card__heading">
                                <span class="card__heading-span card__heading-span-2">{{ event.name }}</span>

                            </div>
                            <div class="card__details">
                                <ul>
                                    <li>Organiser - {{ event.client }}</li>
                                    <li>Location - {{ event.location }}</li>
                                    <li>Date - {{ event.event_date }}</li>
                                    <li>Type - {{ event.advanture.name }}</li>
                                    <li></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card__side  card__side--back card__side--back-2">
                            <div class="card__cta">
                                <div class="back-price-box">
                                    <span class="back-price-box-only">only</span>
                                    <span class="back-price-box-price">${{ event.price }}</span>
                                </div>
                                <a href="#popup" class="btn btn--white"
                                   onclick="showPopup({eventID:'{{ event.id }}', name:'{{ event.name }}', desc: '{{ event.description }}'})">Book
                                    now!</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="popup" id="popup">
            <a class="popup__close-bg" href="#" onclick="history.go(-1)"></a>
            <div class="popup__content" style="padding: 2em">
                <div class="popup__left"> {% static '' %}
                    <img class="popup__img" src="{% static 'myapp/img/nat-8.jpg' %}"
                         alt="popup photo">
                    {#                        <img class="popup__img" src="{% static 'myapp/img/nat-9.jpg' %}" alt="popup photo">#}
                </div>
                <div class="popup__right">
                    <a class="popup__close" href="#" onclick="history.go(-1)">&times;</a>
                    <h2 class="heading-secondary u-padding-bottom-small">Book Your Tickets Now!!!</h2>
                    <h3 class="heading3 u-padding-bottom-small" id="event_name"></h3>
                    <p class="popup__text u-padding-bottom-medium" id="event_desc">

                    </p>
                    <form id="book_form" method="POST" class="form" style="padding-bottom: 1em">
                        {% csrf_token %}
                        <div class="form__group">
                            <input name="number_of_people" style="box-shadow: lightgrey 0em 0em 0.5em 0.1em" min="1"
                                   type="number"
                                   class="form__input" placeholder="Number of Tickets" id="number_of_people"
                                   required>
                            <label for="name" class="form__label">Number of Tickets</label>
                        </div>
                        <div class="u-center-text">
                            <button type="submit" onsubmit="hidePaymentPopup()" class="btn btn--greenfill">Book Now &rarr;</button>
                        </div>
                    </form>


                </div>

            </div>
        </div>

    {% endif %}
    <section class="section-features" id="features">
        <div class="row">
            {% for type in types %}

                <a href="{% url 'myapp1:adventuresdetail' type.pk %}" style="text-decoration: none" class="col-1-of-4">
                    <div class="feature-box">
                        {% if type.name == "Wildlife adventures" %}
                            <i class="feature-box__icon icon icon-basic-world4"></i>
                        {% endif %}
                        {% if type.name == "Extreme adventures" %}
                            <i class="feature-box__icon icon icon-basic-world3"></i>
                        {% endif %}
                        {% if type.name == "Outdoor adventures" %}
                            <i class="feature-box__icon icon icon-basic-world2"></i>
                        {% endif %}
                        {% if type.name == "Water Adventure" %}
                            <i class="feature-box__icon icon icon-basic-world1"></i>
                        {% endif %}
                        <h3 class="heading3 u-margin-bottom-small">{{ type.name }}
                        </h3>
                        <p class="feature-box__text">{{ type.description | truncatechars:160 }}</p>
                    </div>
                </a>



            {% endfor %} </div>
    </section>
{% endblock %}

templates/myapp/messages.html
<style>
    .alert {
        border: 1px solid;
        margin: 10px auto;
        padding: 15px 20px;
        border-radius: 5px;
        text-align: center;
    }

    .alert-success {
        color: #155724;
        background-color: #d4edda;
        border-color: #c3e6cb;
    }

    .alert-danger {
        color: #721c24;
        background-color: #f8d7da;
        border-color: #f5c6cb;
    }

    .alert-info {
        color: #0c5460;
        background-color: #d1ecf1;
        border-color: #bee5eb;
    }

    .alert-wrapper {
        display: flex;
        justify-content: center;
    }
</style>

<div class="alert-wrapper">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}" id="msg" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/myapp/signupSuccess.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <title>Success</title>
</head>
<body>
<h1>{{ msg }}</h1>
<{% endblock %}